/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */

package rsm;

import javax.swing.DefaultListModel;

/**
 *
 * @author paul
 */
public final class ExhibitAgesForm extends javax.swing.JFrame implements FormInterface {
    private ExhibitAgeList exhibitAgeList;
    private ExhibitAge curRecord;
    private int selectedRecord;
    private boolean newItem;
    private final DefaultListModel<String> theListModelData = new DefaultListModel<String>();
    /**
     * Creates new form ExhibitAgesForm
     */
    public ExhibitAgesForm() {
        initComponents();
        lstDisplay.setModel(theListModelData);       
        exhibitAgeList.readList(HeaderRequired.HEADERS);
        createTheList();
        edtHeaders.setText(exhibitAgeList.getHeader());
        setButtons();
        displayTheList();
        newItem = false;  
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

     public void setButtons(){
        boolean test =!this.edtExhibitAgeText.getText().isEmpty() &&
                      !this.edtExhibitAgeValue.getText().isEmpty() &&
                      !this.edtExhibitAgeClass.getText().isEmpty();
        btnDelete.setText("Delete");
        btnUpdate.setText("Update");
        btnInsert.setText("New");
        btnUpdate.setEnabled(test);
        btnDelete.setEnabled(test);
        btnInsert.setEnabled(!test);        
    }
    
    @Override
    public void setButtons(BaseDataItem dataRecord) {
        btnDelete.setText(dataRecord.isReadyToDelete()?"Undelete":"Delete");
        btnUpdate.setText(dataRecord.isDirty()?" Undo ":"Update");
        btnInsert.setText(dataRecord.isNewItem()?"Add":"New");
        btnUpdate.setEnabled(!dataRecord.isReadyToDelete());
        //btnDelete.setEnabled(!dataRecord.isNewItem());
    } 
    
    @Override
    public void createTheList() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void displayTheList() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   @Override
    public ExhibitAge getFormData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setFormData(BaseDataItem formData) {
        ExhibitAge dataRecord = (ExhibitAge) formData; 
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnAbandon = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        edtHeaders = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDisplay = new javax.swing.JList();
        lblExhibitAgeID = new javax.swing.JLabel();
        edtExhibitAgeID = new javax.swing.JTextField();
        lblExhibitAgeValue = new javax.swing.JLabel();
        edtExhibitAgeValue = new javax.swing.JTextField();
        lblExhibitAgeText = new javax.swing.JLabel();
        edtExhibitAgeText = new javax.swing.JTextField();
        lblExhibitAgeClass = new javax.swing.JLabel();
        edtExhibitAgeClass = new javax.swing.JTextField();

        setTitle("Exhibit Age Editor");

        btnInsert.setText("Add");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setText("Save and Close ");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnAbandon.setText("Abandon and Close");
        btnAbandon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonActionPerformed(evt);
            }
        });

        edtHeaders.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        edtHeaders.setText("Header");

        lstDisplay.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        lstDisplay.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDisplayValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstDisplay);

        lblExhibitAgeID.setText("Exhibit Age ID");

        edtExhibitAgeID.setText("0");

        lblExhibitAgeValue.setText("Exhibit Age Value");

        edtExhibitAgeValue.setText("0");

        lblExhibitAgeText.setText("Exhibit Age Text for Exhibit ");

        lblExhibitAgeClass.setText("Exhibit Age Text for Classes");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(lblExhibitAgeClass)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(edtExhibitAgeClass, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(lblExhibitAgeText)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(edtExhibitAgeText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(308, 308, 308))
            .add(layout.createSequentialGroup()
                .add(88, 88, 88)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(lblExhibitAgeValue)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(edtExhibitAgeValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(lblExhibitAgeID)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(edtExhibitAgeID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jScrollPane1)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(523, 523, 523)
                            .add(btnAbandon))
                        .add(layout.createSequentialGroup()
                            .add(545, 545, 545)
                            .add(btnClose))
                        .add(layout.createSequentialGroup()
                            .add(btnDelete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(18, 18, 18)
                            .add(btnUpdate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(btnInsert, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(15, 15, 15)
                            .add(lblStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 506, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(org.jdesktop.layout.GroupLayout.TRAILING, edtHeaders))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(44, 44, 44)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblExhibitAgeID)
                    .add(edtExhibitAgeID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblExhibitAgeValue)
                    .add(edtExhibitAgeValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblExhibitAgeText)
                    .add(edtExhibitAgeText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblExhibitAgeClass)
                    .add(edtExhibitAgeClass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(edtHeaders, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(206, 206, 206)
                    .add(lblStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(43, 43, 43)
                    .add(btnAbandon)
                    .add(20, 20, 20)
                    .add(btnClose)
                    .add(37, 37, 37)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(btnDelete)
                        .add(btnUpdate)
                        .add(btnInsert))
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        newItem = ! newItem;
        if (newItem){
            lblStatus.setText("New Record - Add or Cancel");
            this.edtExhibitAgeID.setText("");
            this.edtExhibitAgeValue.setText("");
            this.edtExhibitAgeClass.setText("");
            this.edtExhibitAgeText.setText("");
            btnInsert.setText("Add");
        } else if (this.edtExhibitAgeClass.getText().isEmpty() || 
                   this.edtExhibitAgeText.getText().isEmpty()  ||
                   this.edtExhibitAgeValue.getText().isEmpty()){
            newItem = true;
            lblStatus.setText("New Record - Not added as data not specified");
        } else {
            lblStatus.setText("New Record - Added");
            ExhibitAge dataRecord = (ExhibitAge) getFormData();
            dataRecord.setNewItem(true);
            exhibitAgeList.add(dataRecord);
            theListModelData.addElement(dataRecord.toListString(exhibitAgeList.getFormatStr()));
            setButtons(dataRecord);
            selectedRecord = exhibitAgeList.list.size();
            curRecord = (ExhibitAge) exhibitAgeList.get(selectedRecord);
            lstDisplay.setSelectedIndex(selectedRecord);
            displayTheList();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        ExhibitAge dataRecord = (ExhibitAge) getFormData();
        dataRecord.setDirty(false);
        dataRecord.setNewItem(false);
        dataRecord.setReadyToDelete(false);
        if (!dataRecord.equals(curRecord)){
            if (curRecord.isDirty()){
                dataRecord.performRead();
                curRecord.setDirty(false);
            } else {
                curRecord.setDirty(true);
                dataRecord.setDirty(true);
            }
            exhibitAgeList.list.set(selectedRecord, dataRecord);
            theListModelData.set(selectedRecord, dataRecord.toListString(exhibitAgeList.getFormatStr()));
        }
        setButtons(dataRecord);
        displayTheList();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //curRecord = getFormData();
        curRecord.setReadyToDelete(!curRecord.isReadyToDelete());
        //btnDelete.setText(curRecord.isReadyToDelete()?"Undelete":"Delete");
        exhibitAgeList.list.set(selectedRecord, curRecord);
        theListModelData.set(selectedRecord, curRecord.toListString(exhibitAgeList.getFormatStr()));
        setButtons(curRecord);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        exhibitAgeList.writeList();
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAbandonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAbandonActionPerformed

    private void lstDisplayValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDisplayValueChanged
        selectedRecord = lstDisplay.getSelectedIndex();
        setFormData((ExhibitAge) exhibitAgeList.get(selectedRecord));
        curRecord = (ExhibitAge) exhibitAgeList.get(selectedRecord);
    }//GEN-LAST:event_lstDisplayValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandon;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField edtExhibitAgeClass;
    private javax.swing.JTextField edtExhibitAgeID;
    private javax.swing.JTextField edtExhibitAgeText;
    private javax.swing.JTextField edtExhibitAgeValue;
    private javax.swing.JTextField edtHeaders;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExhibitAgeClass;
    private javax.swing.JLabel lblExhibitAgeID;
    private javax.swing.JLabel lblExhibitAgeText;
    private javax.swing.JLabel lblExhibitAgeValue;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList lstDisplay;
    // End of variables declaration//GEN-END:variables

 }
